FROM node:22-bullseye AS frontend-release-base
ARG NODE_ENV=development
ENV NODE_ENV=$NODE_ENV
ENV PNPM_VERSION=11.8.0
ENV pnpm='corepack pnpm'
EXPOSE 5173
WORKDIR /opt/aoam-property-plan/frontend/
COPY ./frontend/src/app ./src/app
COPY ./frontend/src/assets ./src/assets
COPY ./frontend/src/common ./src/common
COPY ./frontend/src/layouts ./src/layouts
COPY ./frontend/src/logger ./src/logger
COPY ./frontend/src/pages ./src/pages
COPY ./frontend/src/store ./src/store
COPY ./frontend/src/types ./src/types
COPY ./frontend/src/index.css \
    ./src/main.tsx \
    ./
COPY ./frontend/index.html \
    ./frontend/package.json \
    ./frontend/pnpm-lock.yaml \
    ./frontend/pnpm-workspace.yaml \
    ./frontend/postcss.config.js \
    ./frontend/tsconfig.app.json \
    ./frontend/tsconfig.common.json \
    ./frontend/tsconfig.json \
    ./frontend/tsconfig.node.json \
    ./frontend/tsconfig.test.json \
    ./
RUN corepack enable
RUN corepack use pnpm

FROM frontend-release-base AS frontend-release-build
RUN $pnpm install --frozen-lockfile
RUN $pnpm build

FROM frontend-release-build AS frontend-app
ENTRYPOINT [ "corepack", "pnpm" ]
CMD [ "dev" ]
