[pytest]
addopts = -rA
          -vv
          --color=yes
          --code-highlight=yes
        #   --cov=backend
        #   --cov-report=term-missing
        #   -ra [all excep passed]
        #   -rA [all]
norecursedirs = .*
python_files = test_*.py test.py
required_plugins = pytest-mock>=3.14.0,<4.0.0
                   pytest-sugar>=1.0.0,<2.0.0
                   pytest-xdist>=3.5.0,<4.0.0
