name: "Frontend CI Trigger: PR"

on:
  pull_request:
    paths:
      - ".github/workflows/**.yml"
      - "!.github/workflows/backend-*.yml"
      - "frontend/**/*.ini"
      - "frontend/**/*.py"
      - "frontend/**/*.pyi"
      - "frontend/**/*.toml"
      - "frontend/**/*.yaml"
      - "frontend/**/*.yml"

jobs:
  build:
    uses: ./.github/workflows/frontend-test.yml
